# Generated by Django 4.1.5 on 2023-02-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userdetails',
            new_name='Userdetail',
        ),
    ]
