# Generated by Django 4.1.5 on 2023-02-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0002_rename_userdetails_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentarDetail',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('main_address', models.CharField(max_length=100)),
                ('detailed_address', models.CharField(max_length=500)),
                ('room_details', models.TextField()),
                ('room_vacent', models.IntegerField()),
                ('room_photos', models.ImageField(default='', upload_to='roomphoto')),
            ],
        ),
    ]
