# Generated by Django 4.1.5 on 2023-02-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0003_rentardetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentardetail',
            name='room_photos',
        ),
        migrations.CreateModel(
            name='multipleimage',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('room_photos', models.FileField(default='', upload_to='roomphto')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PG.rentardetail')),
            ],
        ),
    ]
