# Generated by Django 4.1.5 on 2023-02-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0004_remove_rentardetail_room_photos_multipleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='room_photos',
            field=models.FileField(default='', upload_to='room/photo'),
        ),
    ]
