# Generated by Django 4.1.5 on 2023-02-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0008_alter_multipleimage_room_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentardetail',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
