# Generated by Django 4.1.5 on 2023-02-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0009_rentardetail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentardetail',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
