# Generated by Django 4.1.5 on 2023-02-10 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0011_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PG.rentardetail'),
        ),
    ]
