# Generated by Django 4.1.5 on 2023-02-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0012_booking_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('visitor', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
