# Generated by Django 4.1.5 on 2023-02-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0013_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PG.rentardetail'),
        ),
    ]
