# Generated by Django 4.1.5 on 2023-02-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0014_schedule_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentardetail',
            name='map',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
