# Generated by Django 4.1.5 on 2023-02-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0015_rentardetail_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('img', models.ImageField(upload_to='room/proof')),
                ('b_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('status', models.CharField(max_length=30)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PG.booking')),
            ],
        ),
    ]
