# Generated by Django 4.1.5 on 2023-02-20 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0017_booking_b_date_booking_b_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='a_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='month',
            field=models.IntegerField(default=1),
        ),
    ]
