# Generated by Django 4.1.5 on 2023-02-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0019_booking_tfare'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
