# Generated by Django 4.1.5 on 2023-02-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0020_booking_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='remaining_due',
            field=models.IntegerField(default=0),
        ),
    ]
