# Generated by Django 4.1.5 on 2023-02-21 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0022_dueproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueproof',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PG.proof'),
        ),
    ]
